<?php
namespace app\Buffer;

define("WEB2LOGIN", 0);

//WEB2LOGIN_REGISTER_ACCOUNT_REQUEST = 4097 (web平台向Login服务器请求注册XOX-IM账号)
define('WEB2LOGIN_REGISTER_ACCOUNT_REQUEST', 4097);

//WEB2LOGIN_REGISTER_ACCOUNT_REQUEST_ASK = 4098 (web平台向Login服务器请求注册XOX-IM账号的回复)
define('WEB2LOGIN_REGISTER_ACCOUNT_REQUEST_ASK',4098);

//LOGIN2WEB_SERVER_START_REQUEST = 4103 (LOGIN服务器向WEB服务器通知LOGIN服务启动)  (LOGIN服务器的IP+PORT,WEB平台可通过SOCKET连接获取)
define("LOGIN2WEB_SERVER_START_REQUEST", 4103);

//LOGIN2WEB_SERVER_START_REQUEST_ASK = 4104 (LOGIN服务器向WEB服务器通知LOGIN服务启动的回复)
define("LOGIN2WEB_SERVER_START_REQUEST_ASK", 4104);

//CLIENT2WEB_LOGIN_REQUEST = 4107 (客户端向WEB服务器请求LOGIN服务器信息)
define("CLIENT2WEB_LOGIN_REQUEST", 4107);

//CLIENT2WEB_LOGIN_REQUEST_ASK = 4108 (客户端向WEB服务器请求LOGIN服务器信息的回复)
define("CLIENT2WEB_LOGIN_REQUEST_ASK", 4108);

//LOGIN2WEB_INFO_NOTIFY = 4116 (LOGIN服务器向WEB服务器定时通知 LOGIN服务器当前注册，在线人数)
define("LOGIN2WEB_INFO_NOTIFY", 4116);
define("CLIENT2LOGIN_LOGIN_REQUEST",4109);
define("LOGIN2WEB_SESSIONKEY_AUTH",4117);
define("LOGIN2WEB_SESSIONKEY_AUTH_ASK",4118);
